### ISSUE TITLE
Plugin Fritzbox_  (7490 Ver 7.01) läuft auf Error

### ISSUE THREAD

**Issue by adeisboe** [wrzlbrmft/munin-fritzbox#1]
folgende Fehlermeldung wird ins Munin-Log (munin-node.log) geschrieben:
Das Plugin schreibt somit auch keine Daten:

munin-node.log:
2019/05/15-19:55:19 [12434] Error output from fritzbox_:
2019/05/15-19:55:19 [12434] 	/etc/munin/plugins/fritzbox_: line 14: printf: -P: invalid option
2019/05/15-19:55:19 [12434] 	printf: usage: printf [-v var] format [arguments]

Bitte um Feedback: adeisboe@gmail.com
Danke!

**Comment by wrzlbrmft** [comment]
Vorab: Das Script wurde explizit für die Fritzbox 7170 geschrieben.
Und in Zeile 14 des Script ist weder ein printf-Befehl, noch verwendet es irgendwo anders die Option -P.
Um vernünftig helfen zu können brauche ich mehr Informationen:
- Betriebssystem
- bash-Version
- README exakt befolgt?
- Wurde das Script verändert? Wenn ja: Wie?
